name: Pytest

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install testit-cli
    
    - name: Get TEST_RUN_ID from webhook
      run: |
        echo "TEST_RUN_ID: ${{ github.event.client_payload.TEST_RUN_ID }}"
        echo "TEST_RUN_ID=${{ github.event.client_payload.TEST_RUN_ID }}" >> $GITHUB_ENV
    
    - name: Setup TestIT filter
      run: |
        export TMS_TOKEN=ZWQ4M0Vnc3FFZ0t6VlY0QjRO
        testit autotests_filter \
          --url https://team-4y6k.testit.software \
          --configuration-id 0198d162-1544-744f-a04b-3276d36b9e56 \
          --testrun-id $TEST_RUN_ID \
          --framework pytest \
          --disable-cert-validation \
          --output tmp/filter.txt
    
    - name: Run filtered tests
      run: |
        pytest "$(cat tmp/filter.txt)" \
          --tmsConfigurationId=0198d162-1544-744f-a04b-3276d36b9e56 \
          --tmsProjectId=0198d162-1514-7157-a67d-82bd275ba589 \
          --tmsPrivateToken=ZWQ4M0Vnc3FFZ0t6VlY0QjRO \
          --tmsUrl=https://team-4y6k.testit.software \
          --tmsTestRunId=$TEST_RUN_ID \
          --tmsAdapterMode=1 \
          --tmsCertValidation=false \
          --testit